### ISSUE TITLE
Emptying out an ocean led to a crash

### ISSUE THREAD

**Issue by Vaneixus** [lhns/mc-fluid-physics#186]
I run a private minecraft SMP server. I saw that the server was crashing and lagging near a minecraft ocean biome, to my surprise, I find that fluid physics is attempting to empty out an ocean(Minecraft cold ocean) into an underground cave, from what I can see from the aftermath. this of course causes crash because of the amount of physics being simulated.

**Comment by LolHens** [comment]
Hi! Yes emtying large bodies of fluid is expected to cause some lag but it shouldn't crash the game. Do you have a log file?

**Comment by Vaneixus** [comment]
yes here it is.
[crash-2021-12-16_18.56.00-server.txt](https://github.com/LolHens/mc-fluid-physics/files/7736927/crash-2021-12-16_18.56.00-server.txt)

**Comment by LolHens** [comment]
The crashlog suggests that there might be something wrong with your fluidphysics.conf. Could you also send it?

**Comment by Vaneixus** [comment]
[fluidphysics.txt](https://github.com/LolHens/mc-fluid-physics/files/7737839/fluidphysics.txt)
here's the config, and I am using it for vanilla as well, so the server runs server-only mods.

**Comment by LolHens** [comment]
This is a bit weird because the crash log suggests you would have the following configuration:
```
  spring = {
    // Sets the block name which will act as a spring block. Fluid source blocks that are adjacent to spring blocks will behave like in vanilla
    block = "minecraft:",
  }
```
Weirdly this config seems to be set properly in the config file you attached:
```
  spring = {
    // Sets the block name which will act as a spring block. Fluid source blocks that are adjacent to spring blocks will behave like in vanilla
    block = "fluidphysics:spring",
  }
```
