### ISSUE TITLE
Exception Ticking World (1.18.2 Fabric)

### ISSUE THREAD

**Issue by DatrixTHLK** [lhns/mc-fluid-physics#221]
Hi there,

When I try to load up a world it gives me this error:

Crash Log: https://gist.github.com/DatrixTHLK/81c39e57d68703ca3aec2393d10899a1
Crashy Link of where exactly the error is: https://crashy.net/dydKVIDA5TD7wGVP5uyg

I have a feeling this mod doesn't work with fabric 1.18.2. 

Minecraft 1.18.2
Fabric 0.13.3
Fabric API: 0.48.0
Scala (Fabric): 3.0.2
Fluid Physics: 1.6.0

**Comment by lhns** [comment]
Hi! This should be fixed in v1.7.0-1.18.2

**Comment by DatrixTHLK** [comment]
Thanks for the info and response.  I shall use it. I really like this mod
